# Generated by Django 3.1.3 on 2020-11-27 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=25)),
                ('overview', models.TextField()),
                ('content', models.TextField()),
                ('comment', models.IntegerField(default=5)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('articlebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.articlebase')),
                ('price', models.IntegerField(default=0)),
                ('sells', models.IntegerField(default=0)),
                ('starts', models.IntegerField(max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(to='blog.ProductCategory')),
            ],
            bases=('blog.articlebase',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('articlebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.articlebase')),
                ('view', models.IntegerField()),
                ('like', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='blog.PostCategory')),
            ],
            bases=('blog.articlebase',),
        ),
    ]
