# Generated by Django 3.1.3 on 2020-12-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_posts_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='article',
            new_name='post',
        ),
    ]
