# Generated by Django 3.1.3 on 2020-12-06 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ASH', 'آذربایجان شرقی'), ('AGH', 'آذربایجان غربی'), ('ARB', 'اردبیل'), ('ES', 'اصفهان'), ('AL', 'البرز'), ('IL', 'ایلام'), ('BSH', 'بوشهر'), ('TEH', 'تهران'), ('CHKH', 'چهارمحال و بختیاری'), ('KHj', 'خراسان جنوبی'), ('KHR', 'خراسان رضوی'), ('KHSH', 'خراسان شمالی'), ('KHZ', 'خوزستان '), ('ZNJ', 'زنجان'), ('SMN', 'سمنان'), ('SB', 'سیستان و بلوچستان'), ('FA', 'فارس'), ('QHZ', 'قزوین'), ('GHOM', 'قم'), ('KRD', 'کردستان'), ('KRM', 'کرمان'), ('KRSH', 'کرمانشاه'), ('KGB', 'کهگیلویه و بویراحمد'), ('GOL', 'گلستان'), ('GIL', 'گیلان'), ('LOR', 'لرستان'), ('MAZ', 'مازندران'), ('MARZ', 'مرکزی'), ('HRMZ', 'هرمزگان'), ('HMDN', 'همدان'), ('YAZD', 'یزد')], default='TEH', max_length=4)),
                ('address', models.TextField()),
                ('phone_number', models.IntegerField(max_length=9)),
                ('plaque', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
